[secrets]
consumer_key = '45DPd3Rtu73HzBE7PlXTCHCVs'
consumer_secret = 'REg3wWTDe8MODghJQTvmvt4g7TZvZ4TiTGHfSFlUSOKttRpakd'
access_token = '1545772813994250240-ami7gvCQVTXKllcLLu2EmQbQk3Iwgx'
access_token_secret = 'P2UxDeZ4st9HKaxklGdYFyYGDW7COvtCmTugo45iwDASZ'

